<script setup lang="ts">
import { onMounted, reactive, ref } from "vue";
import { useI18n } from "vue-i18n";
import { VButton, VCard, VEmpty, VPageHeader } from "@halo-dev/components";
import { ApiError, api, createStaticBuildTaskId, type LinkGroup, type LocalesConfig, type SiteLink } from "@/api/client";
import { useSessionStore } from "@/stores/session";
import { useCodeLabel } from "@/i18n/useCodeLabel";
import TaskProgress from "@/components/TaskProgress.vue";
import MediaPickerField from "@/components/MediaPickerField.vue";

const session = useSessionStore();
const { t } = useI18n();
const codeLabel = useCodeLabel();
const locales = ref<LocalesConfig>();
const groups = ref<LinkGroup[]>([]);
const items = ref<SiteLink[]>([]);
const selectedGroup = ref<LinkGroup>();
const selectedLink = ref<SiteLink>();
const activeLocale = ref("");
const error = ref("");
const buildTaskIds = ref<string[]>([]);
const groupForm = reactive({ id: "", name: "", description: "", order: 0 });
const linkForm = reactive({ id: "", groupId: "", url: "", logo: "", name: "", description: "", order: 0 });
const localeForm = reactive({ name: "", description: "" });
const structureForm = reactive({ groupId: "", url: "", logo: "", order: 0 });

async function load() { try { locales.value = await api.locales(); const data = await api.links(); groups.value = data.groups; items.value = data.items; activeLocale.value ||= locales.value.sourceLocale; } catch (caught) { error.value = caught instanceof Error ? caught.message : t("linksPage.loadFailed"); } }
onMounted(load);
async function discardTaskIfMissing(taskId: string) { try { await api.task(taskId); } catch (caught) { if (caught instanceof ApiError && caught.status === 404) buildTaskIds.value = buildTaskIds.value.filter((id) => id !== taskId); } }
async function withBuildTask<T>(request: (taskId: string) => Promise<T>) { const taskId = createStaticBuildTaskId(); buildTaskIds.value = [...buildTaskIds.value, taskId]; try { return await request(taskId); } catch (caught) { await discardTaskIfMissing(taskId); throw caught; } }
async function createGroup() { if (!session.session) return; buildTaskIds.value = []; try { await withBuildTask((taskId) => api.createLinkGroup(session.session!.csrfToken, { id: groupForm.id || undefined, name: groupForm.name, description: groupForm.description, order: groupForm.order }, taskId)); Object.assign(groupForm, { id: "", name: "", description: "", order: 0 }); await load(); } catch (caught) { error.value = caught instanceof Error ? caught.message : t("linksPage.createGroupFailed"); } }
async function createLink() { if (!session.session) return; buildTaskIds.value = []; try { await withBuildTask((taskId) => api.createLink(session.session!.csrfToken, { id: linkForm.id || undefined, groupId: linkForm.groupId, url: linkForm.url, logo: linkForm.logo, name: linkForm.name, description: linkForm.description, order: linkForm.order }, taskId)); Object.assign(linkForm, { id: "", groupId: linkForm.groupId, url: "", logo: "", name: "", description: "", order: 0 }); await load(); } catch (caught) { error.value = caught instanceof Error ? caught.message : t("linksPage.createLinkFailed"); } }
function editGroup(group: LinkGroup) { selectedGroup.value = group; selectedLink.value = undefined; activeLocale.value = group.sourceLocale; Object.assign(structureForm, { groupId: "", url: "", logo: "", order: group.order }); loadLocale(); }
function editLink(link: SiteLink) { selectedLink.value = link; selectedGroup.value = undefined; activeLocale.value = link.sourceLocale; Object.assign(structureForm, { groupId: link.groupId, url: link.url, logo: link.logo ?? "", order: link.order }); loadLocale(); }
function loadLocale() { const value = selectedGroup.value?.locales[activeLocale.value] ?? selectedLink.value?.locales[activeLocale.value]; Object.assign(localeForm, { name: value?.name ?? "", description: value?.description ?? "" }); }
async function saveLocale() { if (!session.session) return; buildTaskIds.value = []; try { if (selectedGroup.value) selectedGroup.value = await withBuildTask((taskId) => api.updateLinkGroupLocale(session.session!.csrfToken, selectedGroup.value!.id, activeLocale.value, { revision: selectedGroup.value!.revision, ...localeForm }, taskId)); if (selectedLink.value) selectedLink.value = await withBuildTask((taskId) => api.updateLinkLocale(session.session!.csrfToken, selectedLink.value!.id, activeLocale.value, { revision: selectedLink.value!.revision, ...localeForm }, taskId)); await load(); } catch (caught) { error.value = caught instanceof Error ? caught.message : t("linksPage.saveFailed"); } }
async function saveStructure() { if (!session.session) return; buildTaskIds.value = []; try { if (selectedGroup.value) selectedGroup.value = await withBuildTask((taskId) => api.updateLinkGroup(session.session!.csrfToken, selectedGroup.value!.id, selectedGroup.value!.revision, structureForm.order, taskId)); if (selectedLink.value) selectedLink.value = await withBuildTask((taskId) => api.updateLink(session.session!.csrfToken, selectedLink.value!.id, { revision: selectedLink.value!.revision, groupId: structureForm.groupId, url: structureForm.url, logo: structureForm.logo, order: structureForm.order }, taskId)); await load(); } catch (caught) { error.value = caught instanceof Error ? caught.message : t("linksPage.structureSaveFailed"); } }
async function removeSelected() { if (!session.session) return; const resource = selectedGroup.value ?? selectedLink.value; if (!resource || !window.confirm(t("linksPage.confirmDelete", { name: resource.locales[resource.sourceLocale]?.name ?? resource.id }))) return; buildTaskIds.value = []; try { if (selectedGroup.value) await withBuildTask((taskId) => api.deleteLinkGroup(session.session!.csrfToken, selectedGroup.value!.id, selectedGroup.value!.revision, taskId)); else if (selectedLink.value) await withBuildTask((taskId) => api.deleteLink(session.session!.csrfToken, selectedLink.value!.id, selectedLink.value!.revision, taskId)); selectedGroup.value = undefined; selectedLink.value = undefined; await load(); } catch (caught) { error.value = caught instanceof Error ? caught.message : t("linksPage.deleteFailed"); } }
</script>

<template><div class="page"><VPageHeader :title="t('linksPage.title')"><template #actions><VButton @click="load">{{t("common.refresh")}}</VButton></template></VPageHeader><div class="page-body settings-grid">
  <VCard><h3>{{t("linksPage.groups")}}</h3><div class="provider-form"><label><span>{{t("linksPage.idOptional")}}</span><input v-model="groupForm.id" placeholder="friends" /></label><label><span>{{t("linksPage.name")}}</span><input v-model="groupForm.name" /></label><label><span>{{t("linksPage.description")}}</span><input v-model="groupForm.description" /></label><label><span>{{t("linksPage.order")}}</span><input v-model.number="groupForm.order" type="number" /></label><VButton type="secondary" @click="createGroup">{{t("linksPage.createGroup")}}</VButton></div><button v-for="group in groups" :key="group.id" class="provider-item" @click="editGroup(group)"><strong>{{ group.locales[group.sourceLocale]?.name }}</strong><span>{{ group.id }}</span></button></VCard>
  <VCard><h3>{{t("linksPage.links")}}</h3><div class="provider-form"><label><span>{{t("linksPage.group")}}</span><select v-model="linkForm.groupId"><option value="">{{t("linksPage.choose")}}</option><option v-for="group in groups" :key="group.id" :value="group.id">{{ group.locales[group.sourceLocale]?.name }}</option></select></label><label><span>{{t("linksPage.idOptional")}}</span><input v-model="linkForm.id" placeholder="example-site" /></label><label><span>{{t("linksPage.name")}}</span><input v-model="linkForm.name" /></label><label><span>{{t("linksPage.url")}}</span><input v-model="linkForm.url" placeholder="https://example.com" /></label><MediaPickerField v-model="linkForm.logo" :label="t('linksPage.localLogo')"/><label><span>{{t("linksPage.description")}}</span><input v-model="linkForm.description" /></label><label><span>{{t("linksPage.order")}}</span><input v-model.number="linkForm.order" type="number" /></label><VButton type="secondary" @click="createLink">{{t("linksPage.createLink")}}</VButton></div><button v-for="link in items" :key="link.id" class="provider-item" @click="editLink(link)"><strong>{{ link.locales[link.sourceLocale]?.name }}</strong><span>{{ link.url }}</span></button><VEmpty v-if="!items.length" :title="t('linksPage.empty')" /></VCard>
  <VCard v-if="selectedGroup || selectedLink"><h3>{{t("linksPage.resourceSettings")}}</h3><div class="provider-form"><label v-if="selectedLink"><span>{{t("linksPage.group")}}</span><select v-model="structureForm.groupId"><option v-for="group in groups" :key="group.id" :value="group.id">{{group.locales[group.sourceLocale]?.name}}</option></select></label><label v-if="selectedLink"><span>{{t("linksPage.url")}}</span><input v-model="structureForm.url" /></label><MediaPickerField v-if="selectedLink" v-model="structureForm.logo" :label="t('linksPage.localLogo')"/><label><span>{{t("linksPage.order")}}</span><input v-model.number="structureForm.order" type="number" /></label><VButton type="secondary" @click="saveStructure">{{t("linksPage.saveStructure")}}</VButton></div><h3>{{t("linksPage.localizedCopy")}}</h3><div class="locale-tabs"><button v-for="locale in locales?.enabled.filter(item => item.enabled)" :key="locale.code" :class="{ active: activeLocale === locale.code }" @click="activeLocale = locale.code; loadLocale()">{{ locale.label }} <span v-if="(selectedGroup?.locales ?? selectedLink?.locales)?.[locale.code]" class="locale-origin-badge">{{ codeLabel((selectedGroup?.locales ?? selectedLink?.locales)?.[locale.code]?.origin ?? '') }}</span></button></div><div class="provider-form"><label><span>{{t("linksPage.name")}}</span><input v-model="localeForm.name" /></label><label><span>{{t("linksPage.description")}}</span><textarea v-model="localeForm.description" /></label><VButton type="secondary" @click="saveLocale">{{t("linksPage.saveTranslation")}}</VButton><button type="button" class="text-danger" @click="removeSelected">{{t("common.deleteForever")}}</button></div></VCard>
  <VCard v-if="buildTaskIds.length"><TaskProgress v-for="taskId in buildTaskIds" :key="taskId" :task-id="taskId" /></VCard>
  <div v-if="error" class="form-alert">{{ error }}</div>
</div></div></template>
