<script setup lang="ts">
import { onMounted, reactive, ref } from "vue";
import { useI18n } from "vue-i18n";
import { VButton, VCard, VEmpty, VPageHeader } from "@halo-dev/components";
import { api, type LocalesConfig, type MenuItem, type MenuRecord } from "@/api/client";
import { useSessionStore } from "@/stores/session";
import { useCodeLabel } from "@/i18n/useCodeLabel";
const session=useSessionStore();const {t}=useI18n();const codeLabel=useCodeLabel();const locales=ref<LocalesConfig>();const menus=ref<MenuRecord[]>([]);const selected=ref<MenuRecord>();const selectedItem=ref<MenuItem>();const activeLocale=ref("");const error=ref("");
const menuForm=reactive({id:"",label:""});const itemForm=reactive({id:"",parentId:"",targetKind:"internal" as "internal"|"external",url:"/",label:"",openInNew:false,order:0});const localeLabel=ref("");
const editForm=reactive({parentId:"",targetKind:"internal" as "internal"|"external",url:"/",openInNew:false,order:0});
async function load(){try{locales.value=await api.locales();menus.value=(await api.menus()).items;if(selected.value){const itemID=selectedItem.value?.id;selected.value=menus.value.find(x=>x.id===selected.value?.id);selectedItem.value=itemID?selected.value?.items.find(item=>item.id===itemID):undefined}activeLocale.value||=locales.value.sourceLocale}catch(caught){error.value=caught instanceof Error?caught.message:t("menusPage.loadFailed")}}
onMounted(load);
async function createMenu(){if(!session.session)return;try{selected.value=await api.createMenu(session.session.csrfToken,{id:menuForm.id||undefined,label:menuForm.label});Object.assign(menuForm,{id:"",label:""});await load()}catch(caught){error.value=caught instanceof Error?caught.message:t("menusPage.createFailed")}}
function choose(menu:MenuRecord){selected.value=menu;selectedItem.value=undefined;activeLocale.value=menu.sourceLocale;localeLabel.value=menu.locales[activeLocale.value]?.label??""}
async function addItem(){if(!session.session||!selected.value)return;try{selected.value=await api.addMenuItem(session.session.csrfToken,selected.value.id,{id:itemForm.id||undefined,parentId:itemForm.parentId||undefined,targetKind:itemForm.targetKind,url:itemForm.url,label:itemForm.label,openInNew:itemForm.openInNew,order:itemForm.order,revision:selected.value.revision});Object.assign(itemForm,{id:"",parentId:"",targetKind:"internal",url:"/",label:"",openInNew:false,order:0});await load()}catch(caught){error.value=caught instanceof Error?caught.message:t("menusPage.addFailed")}}
function editItem(item:MenuItem){selectedItem.value=item;activeLocale.value=selected.value?.sourceLocale??"";localeLabel.value=item.locales[activeLocale.value]?.label??"";Object.assign(editForm,{parentId:item.parentId??"",targetKind:item.targetKind,url:item.url,openInNew:item.openInNew,order:item.order})}
function chooseLocale(code:string){activeLocale.value=code;localeLabel.value=(selectedItem.value?.locales??selected.value?.locales)?.[code]?.label??""}
async function saveLocale(){if(!session.session||!selected.value)return;try{selected.value=selectedItem.value?await api.updateMenuItemLocale(session.session.csrfToken,selected.value.id,selectedItem.value.id,activeLocale.value,{revision:selected.value.revision,label:localeLabel.value}):await api.updateMenuLocale(session.session.csrfToken,selected.value.id,activeLocale.value,{revision:selected.value.revision,label:localeLabel.value});await load()}catch(caught){error.value=caught instanceof Error?caught.message:t("menusPage.saveFailed")}}
async function saveStructure(){if(!session.session||!selected.value||!selectedItem.value)return;try{selected.value=await api.updateMenuItem(session.session.csrfToken,selected.value.id,selectedItem.value.id,{revision:selected.value.revision,parentId:editForm.parentId||undefined,targetKind:editForm.targetKind,url:editForm.url,openInNew:editForm.openInNew,order:editForm.order});selectedItem.value=selected.value.items.find(item=>item.id===selectedItem.value?.id);await load()}catch(caught){error.value=caught instanceof Error?caught.message:t("menusPage.structureSaveFailed")}}
async function removeSelected(){if(!session.session||!selected.value)return;const name=(selectedItem.value?.locales??selected.value.locales)[selected.value.sourceLocale]?.label??(selectedItem.value?.id??selected.value.id);if(!window.confirm(t("menusPage.confirmDelete",{name})))return;try{if(selectedItem.value){selected.value=await api.deleteMenuItem(session.session.csrfToken,selected.value.id,selectedItem.value.id,selected.value.revision);selectedItem.value=undefined;activeLocale.value=selected.value.sourceLocale;localeLabel.value=selected.value.locales[activeLocale.value]?.label??""}else{await api.deleteMenu(session.session.csrfToken,selected.value.id,selected.value.revision);selected.value=undefined}await load()}catch(caught){error.value=caught instanceof Error?caught.message:t("menusPage.deleteFailed")}}
</script>
<template><div class="page"><VPageHeader :title="t('menusPage.title')"><template #actions><VButton @click="load">{{t("common.refresh")}}</VButton></template></VPageHeader><div class="page-body settings-grid"><VCard><h3>{{t("menusPage.collections")}}</h3><div class="provider-form"><label><span>{{t("menusPage.idOptional")}}</span><input v-model="menuForm.id" placeholder="primary"/></label><label><span>{{t("menusPage.name")}}</span><input v-model="menuForm.label"/></label><VButton type="secondary" @click="createMenu">{{t("menusPage.create")}}</VButton></div><button v-for="menu in menus" :key="menu.id" class="provider-item" @click="choose(menu)"><strong>{{menu.locales[menu.sourceLocale]?.label}}</strong><span>{{menu.id}}</span></button><VEmpty v-if="!menus.length" :title="t('menusPage.empty')"/></VCard>
	<VCard v-if="selected"><h3>{{selected.locales[selected.sourceLocale]?.label}} · {{t("menusPage.items")}}</h3><div class="provider-form"><label><span>{{t("menusPage.parent")}}</span><select v-model="itemForm.parentId"><option value="">{{t("menusPage.none")}}</option><option v-for="item in selected.items" :key="item.id" :value="item.id">{{item.locales[selected.sourceLocale]?.label}}</option></select></label><label><span>{{t("menusPage.type")}}</span><select v-model="itemForm.targetKind"><option value="internal">{{t("menusPage.internal")}}</option><option value="external">{{t("menusPage.external")}}</option></select></label><label><span>{{t("menusPage.address")}}</span><input v-model="itemForm.url" placeholder="/pages/about-site/"/></label><label><span>{{t("menusPage.label")}}</span><input v-model="itemForm.label"/></label><label><span>{{t("menusPage.order")}}</span><input v-model.number="itemForm.order" type="number"/></label><label class="check-row"><input v-model="itemForm.openInNew" type="checkbox"/>{{t("menusPage.newWindow")}}</label><VButton type="secondary" @click="addItem">{{t("menusPage.addItem")}}</VButton></div><button v-for="item in selected.items" :key="item.id" class="provider-item" @click="editItem(item)"><strong>{{item.locales[selected.sourceLocale]?.label}}</strong><span>{{item.url}}</span></button></VCard>
	<VCard v-if="selected"><template v-if="selectedItem"><h3>{{t("menusPage.structure")}}</h3><div class="provider-form"><label><span>{{t("menusPage.parent")}}</span><select v-model="editForm.parentId"><option value="">{{t("menusPage.none")}}</option><option v-for="item in selected.items.filter(candidate=>candidate.id!==selectedItem?.id)" :key="item.id" :value="item.id">{{item.locales[selected.sourceLocale]?.label}}</option></select></label><label><span>{{t("menusPage.type")}}</span><select v-model="editForm.targetKind"><option value="internal">{{t("menusPage.internal")}}</option><option value="external">{{t("menusPage.external")}}</option></select></label><label><span>{{t("menusPage.address")}}</span><input v-model="editForm.url"/></label><label><span>{{t("menusPage.order")}}</span><input v-model.number="editForm.order" type="number"/></label><label class="check-row"><input v-model="editForm.openInNew" type="checkbox"/>{{t("menusPage.newWindow")}}</label><VButton type="secondary" @click="saveStructure">{{t("menusPage.saveStructure")}}</VButton></div></template><h3>{{t(selectedItem?'menusPage.item':'menusPage.menu')}}{{t("menusPage.localized")}}</h3><div class="locale-tabs"><button v-for="locale in locales?.enabled.filter(x=>x.enabled)" :key="locale.code" :class="{active:activeLocale===locale.code}" @click="chooseLocale(locale.code)">{{locale.label}}<span v-if="(selectedItem?.locales??selected.locales)[locale.code]" class="locale-origin-badge">{{codeLabel((selectedItem?.locales??selected.locales)[locale.code]?.origin??'')}}</span></button></div><div class="provider-form"><label><span>{{t("menusPage.label")}}</span><input v-model="localeLabel"/></label><VButton type="secondary" @click="saveLocale">{{t("menusPage.saveTranslation")}}</VButton><button type="button" class="text-danger" @click="removeSelected">{{t("common.deleteForever")}}</button></div></VCard><div v-if="error" class="form-alert">{{error}}</div></div></div></template>
