<script setup lang="ts">
import { onMounted, reactive, ref } from "vue";
import { useRouter } from "vue-router";
import { useI18n } from "vue-i18n";
import { VButton, VCard, VPageHeader } from "@halo-dev/components";
import { api, type CommentSettings, type LocalesConfig, type MenuRecord, type SiteSettings } from "@/api/client";
import { useSessionStore } from "@/stores/session";
import { setConsoleLocale } from "@/i18n";
const session=useSessionStore();const router=useRouter();const { t }=useI18n();const site=ref<SiteSettings>();const locales=ref<LocalesConfig>();const menus=ref<MenuRecord[]>([]);const activeLocale=ref("");const error=ref("");const notice=ref("");
const general=reactive({baseUrl:"",timezone:"Asia/Shanghai",adminLocale:"zh-CN" as "en"|"zh-CN",primaryMenu:"",idStrategy:"uuid" as "uuid"|"timestamp"});const localized=reactive({title:"",subtitle:"",description:""});const comments=reactive<CommentSettings>({moderation:"pending",pageSize:20,maxLength:2000});
const password=reactive({currentPassword:"",newPassword:"",confirmation:""});const changingPassword=ref(false);
async function load(){try{const[data,localeData,menuData]=await Promise.all([api.settings(),api.locales(),api.menus()]);site.value=data.site;locales.value=localeData;menus.value=menuData.items;Object.assign(general,{baseUrl:data.site.baseUrl??"",timezone:data.site.timezone,adminLocale:data.site.adminLocale,primaryMenu:data.site.primaryMenu??"",idStrategy:data.site.idStrategy||"uuid"});Object.assign(comments,data.comments);activeLocale.value||=data.site.sourceLocale;loadLocale()}catch(caught){error.value=caught instanceof Error?caught.message:t("settingsPage.loadFailed")}}
onMounted(load);function loadLocale(){const value=site.value?.locales[activeLocale.value];Object.assign(localized,{title:value?.title??"",subtitle:value?.subtitle??"",description:value?.description??""})}
async function saveGeneral(){if(!session.session)return;try{const result=await api.updateSiteSettings(session.session.csrfToken,general);site.value=result.site;setConsoleLocale(general.adminLocale);notice.value=result.build.status==="succeeded"?t("settingsPage.sitePublished"):t("settingsPage.siteBuildFailed")}catch(caught){error.value=caught instanceof Error?caught.message:t("settingsPage.saveFailed")}}
async function saveLocale(){if(!session.session)return;try{const result=await api.updateSiteLocale(session.session.csrfToken,activeLocale.value,localized);site.value=result.site;notice.value=result.build.status==="succeeded"?t("settingsPage.localePublished"):t("settingsPage.localeBuildFailed")}catch(caught){error.value=caught instanceof Error?caught.message:t("settingsPage.saveFailed")}}
async function saveComments(){if(!session.session)return;try{Object.assign(comments,await api.updateCommentSettings(session.session.csrfToken,comments));notice.value=t("settingsPage.commentsSaved")}catch(caught){error.value=caught instanceof Error?caught.message:t("settingsPage.saveFailed")}}
async function changePassword(){if(!session.session)return;error.value="";if(password.newPassword!==password.confirmation){error.value=t("settingsPage.passwordMismatch");return}changingPassword.value=true;try{await api.changePassword(session.session.csrfToken,{currentPassword:password.currentPassword,newPassword:password.newPassword});session.expire();await router.replace({name:"login",query:{passwordChanged:"1"}})}catch(caught){error.value=caught instanceof Error?caught.message:t("settingsPage.passwordChangeFailed")}finally{changingPassword.value=false}}
</script>
<template><div class="page"><VPageHeader :title="t('settingsPage.title')"/><div class="page-body settings-grid"><div v-if="notice" class="form-success">{{notice}}</div><div v-if="error" class="form-alert">{{error}}</div><VCard><div class="provider-form"><h3>{{t("settingsPage.site")}}</h3><label><span>{{t("settingsPage.publicBaseUrl")}}</span><input v-model="general.baseUrl" placeholder="https://blog.example.com"/></label><label><span>{{t("settingsPage.timezone")}}</span><input v-model="general.timezone" placeholder="Asia/Shanghai"/></label><label><span>{{t("settingsPage.consoleLocale")}}</span><select v-model="general.adminLocale"><option value="zh-CN">简体中文</option><option value="en">English</option></select></label><label><span>{{t("settingsPage.primaryMenu")}}</span><select v-model="general.primaryMenu"><option value="">{{t("settingsPage.firstMenu")}}</option><option v-for="menu in menus" :key="menu.id" :value="menu.id">{{menu.locales[menu.sourceLocale]?.label}}</option></select></label><label><span>{{t("settingsPage.idStrategy")}}</span><select v-model="general.idStrategy"><option value="uuid">{{t("settingsPage.compactUuid")}}</option><option value="timestamp">{{t("settingsPage.millisecondTimestamp")}}</option></select><small>{{t("settingsPage.idStrategyHelp")}}</small></label><VButton type="secondary" @click="saveGeneral">{{t("settingsPage.saveSite")}}</VButton></div></VCard>
<VCard><h3>{{t("settingsPage.localizedSite")}}</h3><div class="locale-tabs"><button v-for="locale in locales?.enabled.filter(x=>x.enabled)" :key="locale.code" :class="{active:activeLocale===locale.code}" @click="activeLocale=locale.code;loadLocale()">{{locale.label}}<span v-if="site?.locales[locale.code]" class="locale-origin-badge">{{t("common.configured")}}</span></button></div><div class="provider-form"><label><span>{{t("settingsPage.siteTitle")}}</span><input v-model="localized.title"/></label><label><span>{{t("settingsPage.subtitle")}}</span><input v-model="localized.subtitle"/></label><label><span>{{t("settingsPage.description")}}</span><textarea v-model="localized.description" rows="4"/></label><VButton type="secondary" @click="saveLocale">{{t("settingsPage.saveAndPublish")}}</VButton></div></VCard>
<VCard><div class="provider-form"><h3>{{t("settingsPage.comments")}}</h3><label><span>{{t("settingsPage.moderation")}}</span><select v-model="comments.moderation"><option value="pending">{{t("settingsPage.pending")}}</option><option value="none">{{t("settingsPage.none")}}</option></select></label><label><span>{{t("settingsPage.pageSize")}}</span><input v-model.number="comments.pageSize" type="number" min="1" max="100"/></label><label><span>{{t("settingsPage.maxLength")}}</span><input v-model.number="comments.maxLength" type="number" min="100" max="10000"/></label><VButton type="secondary" @click="saveComments">{{t("settingsPage.saveComments")}}</VButton></div></VCard>
<VCard><form class="provider-form" @submit.prevent="changePassword"><h3>{{t("settingsPage.security")}}</h3><p>{{t("settingsPage.passwordHelp")}}</p><label><span>{{t("settingsPage.currentPassword")}}</span><input v-model="password.currentPassword" type="password" autocomplete="current-password" required/></label><label><span>{{t("settingsPage.newPassword")}}</span><input v-model="password.newPassword" type="password" autocomplete="new-password" minlength="12" maxlength="256" required/></label><label><span>{{t("settingsPage.confirmPassword")}}</span><input v-model="password.confirmation" type="password" autocomplete="new-password" minlength="12" maxlength="256" required/></label><VButton type="secondary" :loading="changingPassword" @click="changePassword">{{t("settingsPage.changePassword")}}</VButton></form></VCard></div></div></template>
